### ISSUE TITLE
TypeError: '<' not supported between instances of 'NoneType' and 'float'

### ISSUE THREAD

**Issue by stephane-caron** [qpsolvers/qpbenchmark#99]
### Summary

This can happen when running the benchmark with calls to a new solver:

```
Traceback (most recent call last):
  File "/.../.micromamba/envs/qpbenchmark/bin/qpbenchmark", line 8, in <module>
    sys.exit(main())
  File "/.../.micromamba/envs/qpbenchmark/lib/python3.10/site-packages/qpbenchmark/benchmark.py", line 309, in main
    report(args, results)
  File "/.../.micromamba/envs/qpbenchmark/lib/python3.10/site-packages/qpbenchmark/benchmark.py", line 252, in report
    report.write(md_path)
  File "/.../.micromamba/envs/qpbenchmark/lib/python3.10/site-packages/qpbenchmark/report.py", line 260, in write
    self.__compute_dataframes()
  File "/.../.micromamba/envs/qpbenchmark/lib/python3.10/site-packages/qpbenchmark/report.py", line 241, in __compute_dataframes
    self.__cost_df = self.results.build_shgeom_df(
  File "/.../.micromamba/envs/qpbenchmark/lib/python3.10/site-packages/qpbenchmark/results.py", line 344, in build_shgeom_df
    {
  File "/.../.micromamba/envs/qpbenchmark/lib/python3.10/site-packages/qpbenchmark/results.py", line 345, in <dictcomp>
    settings: self.get_shgeom_for_metric_and_settings(
  File "/.../.micromamba/envs/qpbenchmark/lib/python3.10/site-packages/qpbenchmark/results.py", line 318, in get_shgeom_for_metric_and_settings
    means[solver] = shgeom(column_values, shift)
  File "/.../.micromamba/envs/qpbenchmark/lib/python3.10/site-packages/qpbenchmark/shgeom.py", line 47, in shgeom
    if (v < 0.0).any():
TypeError: '<' not supported between instances of 'NoneType' and 'float'
```

### Reproduction steps

```
qpbenchmark maros_meszaros_dense_posdef.py run
```

### Technical details

- Operating system: Ubuntu 22.04
- Python version: 3.10

**Comment by stephane-caron** [comment]
This happens when the cost error is undefined.
